### PR TITLE
Js DOM crash course

### PR DESCRIPTION
**Pull request by Adeyemi-Timilehin**
This course give in-depth knowledge on Dom

### CODE REVIEW

**Comment by Adeyemi-Timilehin** [comment]
In-depth knowledge on JS DOM

**Comment by tayormi** [comment]
Hi, can you change JS to JavaScript?

**Comment by Adeyemi-Timilehin** [comment]
JavaScript DOM crash course

**Comment by tayormi** [comment]
I meant in your commit. Change JS to JavaScript in your code and push again

**Pull request closed without merging**
